spring:
  application:
    name: product-service
  profiles:
    actives: localhost
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service


server:
  port: 9788

logging:
  level:
    root: off
    com.eleiatech: DEBUG

---

spring:
  profiles: localhost
  cloud:
    config:
      url: http://localhost:8888
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default-schema: stock_management

  data-source:
    url: "jdbc:postgresql://localhost:5432/stock_management"
    username: postgres
    password: 12345

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
